<?php

return [

    'users' => [
        'model' => App\Models\User::class,

        'columns' => [
            'id' => [
                'label' => 'ID',
                'filter' => null,
                'sortable' => true,
            ],
            'name' => [
                'label' => 'Name',
                'filter' => 'text',
                'sortable' => true,
            ],
            'email' => [
                'label' => 'Email',
                'filter' => 'text',
                'sortable' => true,
            ],
            'status' => [
                'label' => 'Status',
                'filter' => 'select',
                'options' => ['active', 'inactive'],
                'sortable' => true,
            ],
            'created_at' => [
                'label' => 'Created At',
                'filter' => 'date',
                'sortable' => true,
            ],
        ],

        'default_columns' => ['id', 'name', 'email', 'status'],
        'default_sort' => ['created_at', 'desc'],
    ],

    'default_columns' => [
        'admin' => ['id', 'name', 'email', 'status'],
        'manager' => ['name', 'email'],
        'user' => ['name']
    ],

    'lead_submissions' => [
        'model' => \App\Models\LeadSubmission::class,
        'columns' => [
            'id' => ['label' => 'ID', 'filter' => null, 'sortable' => true],
            'submitted_at' => ['label' => 'Lead Creation Date', 'filter' => 'date', 'sortable' => true],
            'submission_type' => ['label' => 'Request Type', 'filter' => null, 'sortable' => false],
            'account_number' => ['label' => 'Account Number', 'filter' => 'text', 'sortable' => true],
            'company_name' => ['label' => 'Company Name', 'filter' => 'text', 'sortable' => true],
            'authorized_signatory_name' => ['label' => 'Authorized Signatory', 'filter' => 'text', 'sortable' => false],
            'email' => ['label' => 'Email', 'filter' => 'text', 'sortable' => true],
            'contact_number_gsm' => ['label' => 'Contact (GSM)', 'filter' => 'text', 'sortable' => false],
            'alternate_contact_number' => ['label' => 'Alternate Contact', 'filter' => 'text', 'sortable' => false],
            'address' => ['label' => 'Address', 'filter' => null, 'sortable' => false],
            'emirate' => ['label' => 'Emirate', 'filter' => 'text', 'sortable' => false],
            'location_coordinates' => ['label' => 'Location Coordinates', 'filter' => null, 'sortable' => false],
            'category' => ['label' => 'Service Category', 'filter' => 'select', 'sortable' => true],
            'type' => ['label' => 'Service Type', 'filter' => 'select', 'sortable' => true],
            'product' => ['label' => 'Product', 'filter' => 'text', 'sortable' => true],
            'offer' => ['label' => 'Offer', 'filter' => null, 'sortable' => false],
            'mrc_aed' => ['label' => 'MRC (AED)', 'filter' => null, 'sortable' => true],
            'quantity' => ['label' => 'Qty', 'filter' => null, 'sortable' => true],
            'ae_domain' => ['label' => 'AE Domain', 'filter' => null, 'sortable' => false],
            'gaid' => ['label' => 'GAID', 'filter' => null, 'sortable' => false],
            'remarks' => ['label' => 'Remarks', 'filter' => null, 'sortable' => false],
            'sales_agent' => ['label' => 'Sales Agent', 'filter' => null, 'sortable' => true],
            'team_leader' => ['label' => 'Team Leader', 'filter' => null, 'sortable' => true],
            'manager' => ['label' => 'Manager', 'filter' => null, 'sortable' => true],
            'status' => ['label' => 'Status', 'filter' => 'select', 'sortable' => true],
            'sla_timer' => ['label' => 'SLA Timer', 'filter' => null, 'sortable' => false],
            'executive' => ['label' => 'Back Office Executive', 'filter' => null, 'sortable' => true],
            'status_changed_at' => ['label' => 'Last Updated', 'filter' => 'date', 'sortable' => true],
            'updated_at' => ['label' => 'Updated', 'filter' => 'date', 'sortable' => true],
            'creator' => ['label' => 'Created By', 'filter' => null, 'sortable' => false],
            'call_verification' => ['label' => 'Call Verification', 'filter' => null, 'sortable' => false],
            'pending_from_sales' => ['label' => 'Pending From Sales', 'filter' => null, 'sortable' => false],
            'documents_verification' => ['label' => 'Documents Verification', 'filter' => null, 'sortable' => false],
            'submission_date_from' => ['label' => 'Submission Date From', 'filter' => 'date', 'sortable' => false],
            'back_office_notes' => ['label' => 'Back Office Notes', 'filter' => null, 'sortable' => false],
            'activity' => ['label' => 'Activity', 'filter' => null, 'sortable' => false],
            'back_office_account' => ['label' => 'Back Office Account', 'filter' => null, 'sortable' => false],
            'work_order' => ['label' => 'Work Order', 'filter' => null, 'sortable' => false],
            'du_status' => ['label' => 'DU Status', 'filter' => null, 'sortable' => false],
            'completion_date' => ['label' => 'Completion Date', 'filter' => 'date', 'sortable' => false],
            'du_remarks' => ['label' => 'DU Remarks', 'filter' => null, 'sortable' => false],
            'additional_note' => ['label' => 'Additional Note', 'filter' => null, 'sortable' => false],
        ],
        'default_columns' => ['id', 'submitted_at', 'submission_type', 'account_number', 'company_name', 'category', 'type', 'product', 'mrc_aed', 'quantity', 'manager', 'team_leader', 'sales_agent', 'status', 'executive', 'sla_timer', 'status_changed_at', 'creator', 'email', 'contact_number_gsm'],
        'default_sort' => ['submitted_at', 'desc'],
        'sla_days' => 7,
    ],

    'field_submissions' => [
        'model' => \App\Models\FieldSubmission::class,
        'columns' => [
            'id' => ['label' => 'ID', 'filter' => null, 'sortable' => true],
            'submitted_at' => ['label' => 'Submission Date', 'filter' => 'date', 'sortable' => true],
            'created_at' => ['label' => 'Created', 'filter' => 'date', 'sortable' => true],
            'company_name' => ['label' => 'Company Name', 'filter' => 'text', 'sortable' => true],
            'contact_number' => ['label' => 'Contact Number', 'filter' => 'text', 'sortable' => true],
            'product' => ['label' => 'Product', 'filter' => 'text', 'sortable' => true],
            'emirates' => ['label' => 'Emirates', 'filter' => 'text', 'sortable' => true],
            'complete_address' => ['label' => 'Address', 'filter' => null, 'sortable' => false],
            'sales_agent' => ['label' => 'Sales Agent', 'filter' => null, 'sortable' => true],
            'team_leader' => ['label' => 'Team Leader', 'filter' => null, 'sortable' => true],
            'manager' => ['label' => 'Manager', 'filter' => null, 'sortable' => true],
            'field_agent' => ['label' => 'Field Agent', 'filter' => null, 'sortable' => true],
            'status' => ['label' => 'Status', 'filter' => 'select', 'sortable' => true],
            'field_status' => ['label' => 'Status', 'filter' => 'select', 'sortable' => true],
            'target_date' => ['label' => 'Target Date', 'filter' => 'date', 'sortable' => true],
            'sla_timer' => ['label' => 'SLA Timer', 'filter' => null, 'sortable' => true],
            'sla_status' => ['label' => 'SLA Status', 'filter' => null, 'sortable' => true],
            'last_updated' => ['label' => 'Last Updated', 'filter' => 'date', 'sortable' => true],
            'creator' => ['label' => 'Created By', 'filter' => null, 'sortable' => false],
        ],
        'default_columns' => ['submitted_at', 'company_name', 'emirates', 'product', 'sales_agent', 'team_leader', 'manager', 'field_agent', 'field_status', 'target_date', 'sla_timer', 'sla_status', 'last_updated'],
        'default_sort' => ['created_at', 'desc'],
    ],

    'customer_support_submissions' => [
        'model' => \App\Models\CustomerSupportSubmission::class,
        'columns' => [
            'id' => ['label' => 'ID', 'filter' => null, 'sortable' => true],
            'submitted_at' => ['label' => 'Submission Date', 'filter' => 'date', 'sortable' => true],
            'created_at' => ['label' => 'Created', 'filter' => 'date', 'sortable' => true],
            'issue_category' => ['label' => 'Issue Category', 'filter' => 'select', 'sortable' => true],
            'company_name' => ['label' => 'Company Name', 'filter' => 'text', 'sortable' => true],
            'account_number' => ['label' => 'Account Number', 'filter' => 'text', 'sortable' => true],
            'contact_number' => ['label' => 'Contact Number', 'filter' => 'text', 'sortable' => true],
            'issue_description' => ['label' => 'Issue Description', 'filter' => null, 'sortable' => false],
            'attachments' => ['label' => 'Attachments', 'filter' => null, 'sortable' => false],
            'manager' => ['label' => 'Manager', 'filter' => null, 'sortable' => true],
            'team_leader' => ['label' => 'Team Leader', 'filter' => null, 'sortable' => true],
            'sales_agent' => ['label' => 'Sales Agent', 'filter' => null, 'sortable' => true],
            'status' => ['label' => 'Status', 'filter' => 'select', 'sortable' => true],
            'creator' => ['label' => 'Created By', 'filter' => null, 'sortable' => false],
        ],
        'default_columns' => ['id', 'submitted_at', 'issue_category', 'company_name', 'account_number', 'contact_number', 'manager', 'team_leader', 'sales_agent', 'status', 'creator'],
        'default_sort' => ['submitted_at', 'desc'],
    ],

    'vas_request_submissions' => [
        'model' => \App\Models\VasRequestSubmission::class,
        'columns' => [
            'id' => ['label' => 'ID', 'filter' => null, 'sortable' => true],
            'submitted_at' => ['label' => 'Submission Date', 'filter' => 'date', 'sortable' => true],
            'created_at' => ['label' => 'Created', 'filter' => 'date', 'sortable' => true],
            'request_type' => ['label' => 'Request Type', 'filter' => 'select', 'sortable' => true],
            'account_number' => ['label' => 'Account Number', 'filter' => 'text', 'sortable' => true],
            'company_name' => ['label' => 'Company Name', 'filter' => 'text', 'sortable' => true],
            'description' => ['label' => 'Description', 'filter' => null, 'sortable' => false],
            'manager' => ['label' => 'Manager', 'filter' => null, 'sortable' => true],
            'team_leader' => ['label' => 'Team Leader', 'filter' => null, 'sortable' => true],
            'sales_agent' => ['label' => 'Sales Agent', 'filter' => null, 'sortable' => true],
            'executive' => ['label' => 'Back Office Executive', 'filter' => null, 'sortable' => true],
            'status' => ['label' => 'Status', 'filter' => 'select', 'sortable' => true],
            'creator' => ['label' => 'Created By', 'filter' => null, 'sortable' => false],
        ],
        'default_columns' => ['id', 'submitted_at', 'request_type', 'account_number', 'company_name', 'manager', 'team_leader', 'sales_agent', 'executive', 'status', 'creator'],
        'default_sort' => ['submitted_at', 'desc'],
    ],

    'email_follow_ups' => [
        'model' => \App\Models\EmailFollowUp::class,
        'columns' => [
            'id' => ['label' => 'ID', 'filter' => null, 'sortable' => true],
            'email_date' => ['label' => 'Email Date', 'filter' => 'date', 'sortable' => true],
            'subject' => ['label' => 'Subject', 'filter' => 'text', 'sortable' => true],
            'category' => ['label' => 'Category', 'filter' => 'select', 'sortable' => true],
            'request_from' => ['label' => 'Request From', 'filter' => 'text', 'sortable' => true],
            'sent_to' => ['label' => 'Sent To', 'filter' => 'text', 'sortable' => true],
            'creator' => ['label' => 'Added By', 'filter' => null, 'sortable' => true],
            'status' => ['label' => 'Status', 'filter' => 'select', 'sortable' => true],
            'status_date' => ['label' => 'Status Date', 'filter' => null, 'sortable' => true],
        ],
        'default_columns' => ['id', 'email_date', 'subject', 'category', 'request_from', 'sent_to', 'creator', 'status', 'status_date'],
        'default_sort' => ['email_date', 'desc'],
    ],

    'employees' => [
        'model' => \App\Models\User::class,
        'columns' => [
            'id' => ['label' => 'ID', 'filter' => null, 'sortable' => true],
            'employee_number' => ['label' => 'Employee ID', 'filter' => 'text', 'sortable' => true],
            'name' => ['label' => 'Employee Name', 'filter' => 'text', 'sortable' => true],
            'roles' => ['label' => 'Role(s)', 'filter' => null, 'sortable' => false],
            'team_leader' => ['label' => 'Team Leader', 'filter' => null, 'sortable' => true],
            'manager' => ['label' => 'Manager', 'filter' => null, 'sortable' => true],
            'department' => ['label' => 'Department', 'filter' => 'select', 'sortable' => true],
            'email' => ['label' => 'Primary Email', 'filter' => 'text', 'sortable' => true],
            'phone' => ['label' => 'Contact No', 'filter' => null, 'sortable' => true],
            'cnic_number' => ['label' => 'GMIC No', 'filter' => null, 'sortable' => true],
            'extension' => ['label' => 'Extension', 'filter' => null, 'sortable' => true],
            'status' => ['label' => 'Status', 'filter' => 'select', 'sortable' => true],
            'joining_date' => ['label' => 'Joining Date', 'filter' => 'date', 'sortable' => true],
            'terminate_date' => ['label' => 'Terminate Date', 'filter' => 'date', 'sortable' => true],
        ],
        'default_columns' => ['id', 'employee_number', 'name', 'roles', 'team_leader', 'manager', 'department', 'email', 'phone', 'cnic_number', 'extension', 'status', 'joining_date', 'terminate_date'],
        'default_sort' => ['name', 'asc'],
    ],

];
