<?php

return [

    'users' => [
        'model' => App\Models\User::class,

        'columns' => [
            'id' => ['label' => 'ID', 'filter' => null, 'sortable' => true],
            'name' => ['label' => 'User', 'filter' => 'text', 'sortable' => true],
            'email' => ['label' => 'Email', 'filter' => 'text', 'sortable' => true],
            'phone' => ['label' => 'Phone', 'filter' => 'text', 'sortable' => true],
            'country' => ['label' => 'Country', 'filter' => 'text', 'sortable' => true],
            'roles' => ['label' => 'Assigned Roles', 'filter' => null, 'sortable' => false],
            'status' => ['label' => 'Status', 'filter' => 'select', 'sortable' => true],
            'last_login_at' => ['label' => 'Last Login', 'filter' => null, 'sortable' => false],
            'created_at' => ['label' => 'Created Date', 'filter' => 'date', 'sortable' => true],
            'employee_number' => ['label' => 'Employee ID', 'filter' => 'text', 'sortable' => true],
            'department' => ['label' => 'Department', 'filter' => 'text', 'sortable' => true],
            'extension' => ['label' => 'Extension', 'filter' => 'text', 'sortable' => true],
            'joining_date' => ['label' => 'Joining Date', 'filter' => 'date', 'sortable' => true],
            'terminate_date' => ['label' => 'Terminate Date', 'filter' => 'date', 'sortable' => true],
            'manager' => ['label' => 'Manager', 'filter' => null, 'sortable' => true],
            'team_leader' => ['label' => 'Team Leader', 'filter' => null, 'sortable' => true],
        ],

        'default_columns' => ['id', 'name', 'email', 'phone', 'country', 'roles', 'status', 'last_login_at', 'created_at'],
        'default_sort' => ['name', 'asc'],
    ],

    'default_columns' => [
        'admin' => ['id', 'name', 'email', 'status'],
        'manager' => ['name', 'email'],
        'user' => ['name']
    ],

    'lead_submissions' => [
        'model' => \App\Models\LeadSubmission::class,
        'columns' => [
            'id' => ['label' => 'ID', 'filter' => null, 'sortable' => true],
            'submitted_at' => ['label' => 'Lead Creation Date', 'filter' => 'date', 'sortable' => true],
            'submission_type' => ['label' => 'Request Type', 'filter' => null, 'sortable' => false],
            'account_number' => ['label' => 'Account Number', 'filter' => 'text', 'sortable' => true],
            'company_name' => ['label' => 'Company Name', 'filter' => 'text', 'sortable' => true],
            'authorized_signatory_name' => ['label' => 'Authorized Signatory', 'filter' => 'text', 'sortable' => false],
            'email' => ['label' => 'Email', 'filter' => 'text', 'sortable' => true],
            'contact_number_gsm' => ['label' => 'Contact Number', 'filter' => 'text', 'sortable' => false],
            'alternate_contact_number' => ['label' => 'Alternate Contact', 'filter' => 'text', 'sortable' => false],
            'address' => ['label' => 'Address', 'filter' => null, 'sortable' => false],
            'emirate' => ['label' => 'Emirate', 'filter' => 'text', 'sortable' => false],
            'location_coordinates' => ['label' => 'Location Coordinates', 'filter' => null, 'sortable' => false],
            'category' => ['label' => 'Service Category', 'filter' => 'select', 'sortable' => true],
            'type' => ['label' => 'Service Type', 'filter' => 'select', 'sortable' => true],
            'product' => ['label' => 'Product', 'filter' => 'text', 'sortable' => true],
            'offer' => ['label' => 'Offer', 'filter' => null, 'sortable' => false],
            'mrc_aed' => ['label' => 'MRC (AED)', 'filter' => null, 'sortable' => true],
            'quantity' => ['label' => 'Qty', 'filter' => null, 'sortable' => true],
            'ae_domain' => ['label' => 'AE Domain', 'filter' => null, 'sortable' => false],
            'gaid' => ['label' => 'GAID', 'filter' => null, 'sortable' => false],
            'remarks' => ['label' => 'Remarks', 'filter' => null, 'sortable' => false],
            'sales_agent' => ['label' => 'Sales Agent', 'filter' => null, 'sortable' => true],
            'team_leader' => ['label' => 'Team Leader', 'filter' => null, 'sortable' => true],
            'manager' => ['label' => 'Manager', 'filter' => null, 'sortable' => true],
            'status' => ['label' => 'Status', 'filter' => 'select', 'sortable' => true],
            'sla_timer' => ['label' => 'SLA Timer', 'filter' => null, 'sortable' => false],
            'executive' => ['label' => 'Back Office Executive', 'filter' => null, 'sortable' => true],
            'status_changed_at' => ['label' => 'Last Updated', 'filter' => 'date', 'sortable' => true],
            'updated_at' => ['label' => 'Updated', 'filter' => 'date', 'sortable' => true],
            'creator' => ['label' => 'Created By', 'filter' => null, 'sortable' => false],
            'call_verification' => ['label' => 'Call Verification', 'filter' => null, 'sortable' => false],
            'pending_from_sales' => ['label' => 'Pending From Sales', 'filter' => null, 'sortable' => false],
            'documents_verification' => ['label' => 'Documents Verification', 'filter' => null, 'sortable' => false],
            'submission_date_from' => ['label' => 'Submission Date From', 'filter' => 'date', 'sortable' => false],
            'back_office_notes' => ['label' => 'Back Office Notes', 'filter' => null, 'sortable' => false],
            'activity' => ['label' => 'Activity', 'filter' => null, 'sortable' => false],
            'back_office_account' => ['label' => 'Back Office Account', 'filter' => null, 'sortable' => false],
            'work_order' => ['label' => 'Work Order', 'filter' => null, 'sortable' => false],
            'du_status' => ['label' => 'DU Status', 'filter' => null, 'sortable' => false],
            'completion_date' => ['label' => 'Completion Date', 'filter' => 'date', 'sortable' => false],
            'du_remarks' => ['label' => 'DU Remarks', 'filter' => null, 'sortable' => false],
            'additional_note' => ['label' => 'Additional Note', 'filter' => null, 'sortable' => false],
        ],
        'default_columns' => ['id', 'submitted_at', 'submission_type', 'account_number', 'company_name', 'category', 'type', 'product', 'mrc_aed', 'quantity', 'manager', 'team_leader', 'sales_agent', 'status', 'executive', 'sla_timer', 'status_changed_at', 'creator', 'email', 'contact_number_gsm'],
        'default_sort' => ['submitted_at', 'desc'],
        'sla_days' => 7,
    ],

    'field_submissions' => [
        'model' => \App\Models\FieldSubmission::class,
        'columns' => [
            'id' => ['label' => 'ID', 'filter' => null, 'sortable' => true],
            'created_at' => ['label' => 'Created', 'filter' => 'date', 'sortable' => true],
            'company_name' => ['label' => 'Company Name', 'filter' => 'text', 'sortable' => true],
            'contact_number' => ['label' => 'Contact Number', 'filter' => 'text', 'sortable' => true],
            'product' => ['label' => 'Product', 'filter' => 'text', 'sortable' => true],
            'emirates' => ['label' => 'Emirates', 'filter' => 'text', 'sortable' => true],
            'complete_address' => ['label' => 'Address', 'filter' => null, 'sortable' => false],
            'sales_agent' => ['label' => 'Sales Agent', 'filter' => null, 'sortable' => true],
            'team_leader' => ['label' => 'Team Leader', 'filter' => null, 'sortable' => true],
            'manager' => ['label' => 'Manager', 'filter' => null, 'sortable' => true],
            'field_agent' => ['label' => 'Field Agent', 'filter' => null, 'sortable' => true],
            'status' => ['label' => 'Status', 'filter' => 'select', 'sortable' => true],
            'field_status' => ['label' => 'Status', 'filter' => 'select', 'sortable' => true],
            'target_date' => ['label' => 'Target Date', 'filter' => 'date', 'sortable' => true],
            'sla_timer' => ['label' => 'SLA Timer', 'filter' => null, 'sortable' => true],
            'sla_status' => ['label' => 'SLA Status', 'filter' => null, 'sortable' => true],
            'last_updated' => ['label' => 'Last Updated', 'filter' => 'date', 'sortable' => true],
            'creator' => ['label' => 'Created By', 'filter' => null, 'sortable' => false],
        ],
        'default_columns' => ['created_at', 'company_name', 'contact_number', 'emirates', 'product', 'complete_address', 'sales_agent', 'team_leader', 'manager', 'field_agent', 'field_status', 'target_date', 'sla_timer', 'sla_status', 'last_updated', 'creator'],
        'default_sort' => ['created_at', 'desc'],
    ],

    'customer_support_submissions' => [
        'model' => \App\Models\CustomerSupportSubmission::class,
        'columns' => [
            'id' => ['label' => 'ID', 'filter' => null, 'sortable' => true],
            'submitted_at' => ['label' => 'Submission Date', 'filter' => 'date', 'sortable' => true],
            'ticket_number' => ['label' => 'Ticket ID', 'filter' => 'text', 'sortable' => true],
            'account_number' => ['label' => 'Account Number', 'filter' => 'text', 'sortable' => true],
            'company_name' => ['label' => 'Company Name', 'filter' => 'text', 'sortable' => true],
            'issue_category' => ['label' => 'Issue Category', 'filter' => 'select', 'sortable' => true],
            'contact_number' => ['label' => 'Contact Number', 'filter' => 'text', 'sortable' => true],
            'issue_description' => ['label' => 'Issue Description', 'filter' => null, 'sortable' => false],
            'creator' => ['label' => 'Submitted By', 'filter' => null, 'sortable' => false],
            'csr' => ['label' => 'CSR Name', 'filter' => null, 'sortable' => true],
            'manager' => ['label' => 'Manager', 'filter' => null, 'sortable' => true],
            'team_leader' => ['label' => 'Team Leader', 'filter' => null, 'sortable' => true],
            'sales_agent' => ['label' => 'Sales Agent', 'filter' => null, 'sortable' => true],
            'status' => ['label' => 'Status', 'filter' => 'select', 'sortable' => true],
            'workflow_status' => ['label' => 'SLA Status', 'filter' => 'select', 'sortable' => true],
            'completion_date' => ['label' => 'Completion Date', 'filter' => 'date', 'sortable' => true],
            'updated_at' => ['label' => 'Last Updated', 'filter' => 'date', 'sortable' => true],
            'created_at' => ['label' => 'Created', 'filter' => 'date', 'sortable' => true],
            'trouble_ticket' => ['label' => 'Trouble Ticket', 'filter' => 'text', 'sortable' => true],
            'activity' => ['label' => 'Activity', 'filter' => null, 'sortable' => false],
            'pending' => ['label' => 'Pending With', 'filter' => 'select', 'sortable' => true],
            'resolution_remarks' => ['label' => 'Resolution Remarks', 'filter' => null, 'sortable' => false],
            'internal_remarks' => ['label' => 'Internal Remarks', 'filter' => null, 'sortable' => false],
        ],
        'default_columns' => [
            'id', 'submitted_at', 'ticket_number', 'account_number', 'company_name', 'issue_category',
            'contact_number', 'creator', 'csr', 'status', 'workflow_status',
            'pending', 'completion_date', 'updated_at',
            'trouble_ticket', 'activity', 'resolution_remarks', 'internal_remarks',
            'manager', 'team_leader', 'sales_agent',
        ],
        'default_sort' => ['submitted_at', 'desc'],
    ],

    'vas_request_submissions' => [
        'model' => \App\Models\VasRequestSubmission::class,
        'columns' => [
            'id' => ['label' => 'ID', 'filter' => null, 'sortable' => true],
            'created_at' => ['label' => 'Created', 'filter' => 'date', 'sortable' => true],
            'request_type' => ['label' => 'Request Type', 'filter' => 'select', 'sortable' => true],
            'account_number' => ['label' => 'Account Number', 'filter' => 'text', 'sortable' => true],
            'company_name' => ['label' => 'Company Name', 'filter' => 'text', 'sortable' => true],
            'contact_number' => ['label' => 'Contact Number', 'filter' => 'text', 'sortable' => true],
            'description' => ['label' => 'Description', 'filter' => null, 'sortable' => false],
            'additional_notes' => ['label' => 'Additional Notes', 'filter' => null, 'sortable' => false],
            'manager' => ['label' => 'Manager', 'filter' => null, 'sortable' => true],
            'team_leader' => ['label' => 'Team Leader', 'filter' => null, 'sortable' => true],
            'sales_agent' => ['label' => 'Sales Agent', 'filter' => null, 'sortable' => true],
            'executive' => ['label' => 'BO Executive', 'filter' => null, 'sortable' => true],
            'status' => ['label' => 'Status', 'filter' => 'select', 'sortable' => true],
            'approved_at' => ['label' => 'Completion Date', 'filter' => 'date', 'sortable' => true],
            'creator' => ['label' => 'Created By', 'filter' => null, 'sortable' => false],
        ],
        'default_columns' => ['id', 'created_at', 'request_type', 'company_name', 'account_number', 'contact_number', 'description', 'status', 'executive', 'sales_agent', 'approved_at'],
        'default_sort' => ['created_at', 'desc'],
        'sla_days' => 7,
    ],

    'special_requests' => [
        'model' => \App\Models\SpecialRequest::class,
        'columns' => [
            'id' => ['label' => 'ID', 'filter' => null, 'sortable' => true],
            'submitted_at' => ['label' => 'Submission Date', 'filter' => 'date', 'sortable' => true],
            'created_at' => ['label' => 'Created', 'filter' => 'date', 'sortable' => true],
            'company_name' => ['label' => 'Company Name', 'filter' => 'text', 'sortable' => true],
            'account_number' => ['label' => 'Account Number', 'filter' => 'text', 'sortable' => true],
            'request_type' => ['label' => 'Request Type', 'filter' => 'select', 'sortable' => true],
            'complete_address' => ['label' => 'Complete Address', 'filter' => null, 'sortable' => false],
            'special_instruction' => ['label' => 'Special Instruction', 'filter' => null, 'sortable' => false],
            'sales_agent' => ['label' => 'Sales Agent', 'filter' => null, 'sortable' => true],
            'team_leader' => ['label' => 'Team Leader', 'filter' => null, 'sortable' => true],
            'manager' => ['label' => 'Manager', 'filter' => null, 'sortable' => true],
            'status' => ['label' => 'Status', 'filter' => 'select', 'sortable' => true],
            'creator' => ['label' => 'Created By', 'filter' => null, 'sortable' => false],
            'updated_at' => ['label' => 'Last Updated', 'filter' => 'date', 'sortable' => true],
        ],
        'default_columns' => ['id', 'submitted_at', 'company_name', 'account_number', 'request_type', 'complete_address', 'sales_agent', 'team_leader', 'manager', 'status', 'creator', 'updated_at'],
        'default_sort' => ['created_at', 'desc'],
    ],

    'email_follow_ups' => [
        'model' => \App\Models\EmailFollowUp::class,
        'columns' => [
            'id' => ['label' => 'ID', 'filter' => null, 'sortable' => true],
            'email_date' => ['label' => 'Email Date', 'filter' => 'date', 'sortable' => true],
            'subject' => ['label' => 'Subject', 'filter' => 'text', 'sortable' => true],
            'category' => ['label' => 'Category', 'filter' => 'select', 'sortable' => true],
            'request_from' => ['label' => 'Request From', 'filter' => 'text', 'sortable' => true],
            'sent_to' => ['label' => 'Sent To', 'filter' => 'text', 'sortable' => true],
            'creator' => ['label' => 'Added By', 'filter' => null, 'sortable' => true],
            'status' => ['label' => 'Status', 'filter' => 'select', 'sortable' => true],
            'status_date' => ['label' => 'Status Date', 'filter' => null, 'sortable' => true],
        ],
        'default_columns' => ['id', 'email_date', 'subject', 'category', 'request_from', 'sent_to', 'creator', 'status', 'status_date'],
        'default_sort' => ['email_date', 'desc'],
    ],

    'employees' => [
        'model' => \App\Models\User::class,
        'columns' => [
            'id' => ['label' => 'ID', 'filter' => null, 'sortable' => true],
            'employee_number' => ['label' => 'Employee ID', 'filter' => 'text', 'sortable' => true],
            'name' => ['label' => 'Employee Name', 'filter' => 'text', 'sortable' => true],
            'roles' => ['label' => 'Role(s)', 'filter' => null, 'sortable' => false],
            'team_leader' => ['label' => 'Team Leader', 'filter' => null, 'sortable' => true],
            'manager' => ['label' => 'Manager', 'filter' => null, 'sortable' => true],
            'department' => ['label' => 'Department', 'filter' => 'select', 'sortable' => true],
            'email' => ['label' => 'Primary Email', 'filter' => 'text', 'sortable' => true],
            'phone' => ['label' => 'Contact No', 'filter' => null, 'sortable' => true],
            'cnic_number' => ['label' => 'GMIC No', 'filter' => null, 'sortable' => true],
            'extension' => ['label' => 'Extension', 'filter' => null, 'sortable' => true],
            'status' => ['label' => 'Status', 'filter' => 'select', 'sortable' => true],
            'joining_date' => ['label' => 'Joining Date', 'filter' => 'date', 'sortable' => true],
            'terminate_date' => ['label' => 'Terminate Date', 'filter' => 'date', 'sortable' => true],
        ],
        'default_columns' => ['id', 'employee_number', 'name', 'roles', 'team_leader', 'manager', 'department', 'email', 'phone', 'cnic_number', 'extension', 'status', 'joining_date', 'terminate_date'],
        'default_sort' => ['name', 'asc'],
    ],

    'cisco_extensions' => [
        'model' => \App\Models\CiscoExtension::class,
        'columns' => [
            'id' => ['label' => 'ID', 'filter' => null, 'sortable' => true],
            'extension' => ['label' => 'Extension', 'filter' => 'text', 'sortable' => true],
            'landline_number' => ['label' => 'Landline Number', 'filter' => 'text', 'sortable' => true],
            'gateway' => ['label' => 'Gateway', 'filter' => 'select', 'sortable' => true],
            'username' => ['label' => 'User Name', 'filter' => null, 'sortable' => true],
            'password' => ['label' => 'Password', 'filter' => null, 'sortable' => false],
            'status' => ['label' => 'Status', 'filter' => 'select', 'sortable' => true],
            'team_leader' => ['label' => 'Team Leader', 'filter' => null, 'sortable' => true],
            'manager' => ['label' => 'Manager', 'filter' => null, 'sortable' => true],
            'usage' => ['label' => 'Usage', 'filter' => null, 'sortable' => false],
            'assigned_to_name' => ['label' => 'Assigned To', 'filter' => null, 'sortable' => false],
            'comment' => ['label' => 'Comment', 'filter' => null, 'sortable' => false],
            'updated_at' => ['label' => 'Last Updated', 'filter' => 'date', 'sortable' => true],
        ],
        'default_columns' => ['id', 'extension', 'landline_number', 'gateway', 'username', 'password', 'status', 'team_leader', 'manager', 'usage', 'assigned_to_name', 'comment', 'updated_at'],
        'default_sort' => ['extension', 'asc'],
    ],

    'clients' => [
        'model' => \App\Models\Client::class,
        'columns' => [
            'company_name' => ['label' => 'Company Name', 'filter' => 'text', 'sortable' => true],
            'submitted_at' => ['label' => 'Submission Date', 'filter' => 'date', 'sortable' => true],
            'manager' => ['label' => 'Manager Name', 'filter' => null, 'sortable' => true],
            'team_leader' => ['label' => 'Team Leader', 'filter' => null, 'sortable' => true],
            'sales_agent' => ['label' => 'Sales Agent Name', 'filter' => null, 'sortable' => true],
            'status' => ['label' => 'Status', 'filter' => 'select', 'sortable' => true],
            'service_type' => ['label' => 'Service Type', 'filter' => 'text', 'sortable' => true],
            'product_type' => ['label' => 'Product Type', 'filter' => 'text', 'sortable' => true],
            'address' => ['label' => 'Address', 'filter' => null, 'sortable' => false],
            'product_name' => ['label' => 'Product Name', 'filter' => 'text', 'sortable' => true],
            'mrc' => ['label' => 'MRC', 'filter' => null, 'sortable' => true],
            'quantity' => ['label' => 'Quantity', 'filter' => null, 'sortable' => true],
            'other' => ['label' => 'Other', 'filter' => null, 'sortable' => false],
            'migration_numbers' => ['label' => 'Migration Numbers', 'filter' => null, 'sortable' => false],
            'wo_number' => ['label' => 'Work Order', 'filter' => 'text', 'sortable' => true],
            'completion_date' => ['label' => 'Completion Date', 'filter' => 'date', 'sortable' => true],
            'payment_connection' => ['label' => 'Payment Connection', 'filter' => null, 'sortable' => false],
            'contract_type' => ['label' => 'Contract Type', 'filter' => 'text', 'sortable' => true],
            'contract_end_date' => ['label' => 'Contract End Date', 'filter' => 'date', 'sortable' => true],
            'renewal_alert' => ['label' => 'Renewal Alert', 'filter' => null, 'sortable' => true],
            'additional_notes' => ['label' => 'Additional Notes', 'filter' => null, 'sortable' => false],
            'account_number' => ['label' => 'Account Number', 'filter' => 'text', 'sortable' => true],
            'creator' => ['label' => 'Created By', 'filter' => null, 'sortable' => false],
        ],
        'default_columns' => ['company_name', 'submitted_at', 'manager', 'team_leader', 'sales_agent', 'status', 'service_type', 'product_type', 'address', 'product_name', 'mrc', 'quantity', 'other', 'migration_numbers', 'wo_number', 'completion_date', 'payment_connection', 'contract_type', 'contract_end_date', 'renewal_alert', 'additional_notes'],
        'default_sort' => ['submitted_at', 'desc'],
    ],

    'expenses' => [
        'model' => \App\Models\Expense::class,
        'columns' => [
            'id' => ['label' => 'ID', 'filter' => null, 'sortable' => true],
            'expense_date' => ['label' => 'Expense Date', 'filter' => 'date', 'sortable' => true],
            'product_category' => ['label' => 'Product Category', 'filter' => 'select', 'sortable' => true],
            'product_description' => ['label' => 'Product Description', 'filter' => 'text', 'sortable' => true],
            'invoice_number' => ['label' => 'Invoice Number', 'filter' => 'text', 'sortable' => true],
            'vat_amount' => ['label' => 'VAT %', 'filter' => null, 'sortable' => true],
            'amount_without_vat' => ['label' => 'Amount (Without VAT)', 'filter' => null, 'sortable' => true],
            'vat_amount_currency' => ['label' => 'VAT Amount', 'filter' => null, 'sortable' => false],
            'full_amount' => ['label' => 'Total Amount', 'filter' => null, 'sortable' => true],
            'added_by' => ['label' => 'Added By', 'filter' => null, 'sortable' => true],
            'created_at' => ['label' => 'Created Date', 'filter' => 'date', 'sortable' => true],
            'status' => ['label' => 'Status', 'filter' => 'select', 'sortable' => true],
        ],
        'default_columns' => ['status', 'expense_date', 'product_category', 'product_description', 'invoice_number', 'vat_amount', 'amount_without_vat', 'vat_amount_currency', 'full_amount', 'added_by', 'created_at'],
        'default_sort' => ['expense_date', 'desc'],
    ],

];
